### ISSUE TITLE
Access token not showing up

### ISSUE THREAD

**Issue by abelanagy** [aislandener/discord-deckboard#13]
Hey,
I really like this project and it would be awesome if I could also use discord shortcuts. Unfortunately, currently the pop-up does not come up with the access token, hence I have to authenticate every time I open discord.
I am looking forward for your answer.
Ábel from Hungary

**Comment by aislandener** [comment]
Hello Ábel

I remove this popup, and now request authorization when open Deckboard.


Aislan Dener Souza Vicentini
Desenvolvedor Web/Mobile
TI | Aislan Dener Souza Vicentini - MEI
+55 16 98130-3033
***@***.***
https://monodirect.com/aislandener
Em 4 de nov. de 2023 16:06 -0300, Nagy Ábel ***@***.***>, escreveu:

**Comment by nagyabel26** [comment]
Thanks, can I save the authorization, so I don't have to authorize every time I open discord?
