### ISSUE TITLE
State visibility for toggle on/off mute, deafen etc to be better visible

### ISSUE THREAD

**Issue by Simego** [aislandener/discord-deckboard#15]
Just an idea to have different state controll for the TOGGLE on mute and deafen, it helps a lot to have only one button for it

**Comment by Simego** [comment]
i was able to add it by creating the button as custom-value and setting the value on it, wanted to change label/icon for better usage but i can't manage to know how to do it, lack of documentation to build deckboard extensions :/

**Comment by aislandener** [comment]
Hello @Simego,

I tried to do it this way, I have a toggle button but only OBS and StreamLabs have this type of button and there is no plugin that has this toggle button.

If you can, thank you for your time.

**Comment by Simego** [comment]
> Hello @Simego,
> 
> I tried to do it this way, I have a toggle button but only OBS and StreamLabs have this type of button and there is no plugin that has this toggle button.
> 
> If you can, thank you for your time.

I was able to achieve an "ok" solution with your discord-deckboard, not exactly what i wanted but it's usable
![image](https://github.com/aislandener/discord-deckboard/assets/2261559/f540d3fa-1a49-4337-85a1-f1dc9eb47866)

now at least i can see the state, i've added a comment on deckboard issues for an state option to be added or at least something that we can use as a baseline in extensions to allow this

if you want i can create a branch and push what i have
then you just select the toggle
![image](https://github.com/aislandener/discord-deckboard/assets/2261559/3c702cdb-346c-4152-aded-abde3c0e37fa)

**Comment by aislandener** [comment]
Interesting, send me a pull request, which I will test and put in the repository.

 I appreciate the effort

**Comment by Simego** [comment]
> Interesting, send me a pull request, which I will test and put in the repository.
> 
> I appreciate the effort

created the pull request, hope it's a solution that fits, been using it and is quite helpful, hope we get more features to do something better in the future.
