### ISSUE TITLE
I don't have the configs button

### ISSUE THREAD

**Issue by matmat123456** [aislandener/discord-deckboard#5]
![image](https://user-images.githubusercontent.com/97603765/201743894-7a41eeda-e9c2-41bf-a738-da232d423c92.png)
I have discord deckboard installed.

![image](https://user-images.githubusercontent.com/97603765/201743994-a9dd5c7d-9dd0-4d5e-a2dd-20be484206ac.png)

But I can't configurate it .
Can I have help ?

**Comment by DTPAaron** [comment]
upp

**Comment by matmat123456** [comment]
What "upp" ? @DTPAaron

**Comment by matmat123456** [comment]
What "upp" @DTPAaron ?

**Comment by LTRGoose** [comment]
@matmat123456 were you able to find a solution? I'm having the same issue :/

**Comment by matmat123456** [comment]
@LTRGoose I don't have the solution I search it in this moment .
