### ISSUE TITLE
Deckboard dosn't show me options in config

### ISSUE THREAD

**Issue by HDAndreasEST** [aislandener/discord-deckboard#9]
![Screenshot_6](https://user-images.githubusercontent.com/45965758/207789828-6e3032ac-9145-4c1b-9ae4-d4416dac9e47.png)
![Screenshot_7](https://user-images.githubusercontent.com/45965758/207789897-17209073-da6c-45f7-883d-f281f5356c1d.png)

**Comment by osmancitci** [comment]
Add Folder settings.json https://github.com/osmancitci/discord-deckboard/releases/tag/Settings
